spring:
  application:
    name: distribution_system
    teachersListFile: '/home/chihebellefi/Downloads/ens_dist/Enseignants avec code ensiegant responsable.xlsx'

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

