spring:
  application:
    name: distribution_system
    outputFileName: 'assignments.json'
    scriptFilename: 'script.py'
    outputDir: './data'
    scriptDir: 'script'
  datasource:
    #url: jdbc:h2:mem:testdb #for memory
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB