spring:
  application:
    name: distribution_system
    teachersListFile: '/home/chihebellefi/Downloads/ens_dist/mini/Enseignants avec code ensiegant responsable.xlsx'
    teachersUnavailabilyFile: '/home/chihebellefi/Downloads/ens_dist/mini/Souhaits Enseignants.xlsx'
    examDataFile: '/home/chihebellefi/Downloads/ens_dist/mini/repartition_salle.xlsx'
    outputFileName: 'assignments.json'
    outputDir: './data'
  datasource:
    #url: jdbc:h2:mem:testdb #for memory
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB