spring:
  application:
    name: distribution_system
    outputFileName: 'assignments.json'
    outputDir: './data'


    #-----------mail server config -----------------------
  mail:
    host: smtp.gmail.com
    port: 587
    username: competitionisi82@gmail.com

    password: WiemChihebMaher2500.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:h2:mem:testdb #for memory
    #url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB